name: flutter_application_2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0
  carousel_slider:
    git: https://github.com/serenader2014/flutter_carousel_slider
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
  - assets/svg/
  - assets/image/
  - assets/image/lemour.jpg
  - assets/image/lion.jpg
  